### ISSUE TITLE
Does it work with ember-auto-import addon?

### ISSUE THREAD

**Issue by szimek** [simonihmig/ember-cli-bundle-analyzer#17]
I haven't used Ember in a long time and I was quite surprised that I need an addon just to be able to import npm packages in my code. Anyway, my vendor bundle is pretty big and I wanted to check what's inside, but it looks like this addon doesn't show libraries imported via `ember-auto-import` addon. E.g. I'm importing `firebase` npm package and can't see it anywhere on the `/_analyze` page.

Is there a way to see packages imported with `ember-auto-import` as well?

**Comment by simonihmig** [comment]
Yes, unfortunately that is a known problem. It is a problem with the way `ember-auto-import` works. Here's an issue for the upstream library that is used by this addon: https://github.com/stefanpenner/broccoli-concat-analyser/issues/34

Nothing we can do about it here for now, but keeping this open for other users.

**Comment by mansona** [comment]
What is the status of this now that https://github.com/stefanpenner/broccoli-concat-analyser/issues/34 has been closed? 🤔 is it just that it's not possible? is the current best solution to use @ef4's proposed solution to use webpack-bundle-analyzer too?

**Comment by simonihmig** [comment]
Fixed by #26
