### ISSUE TITLE
Does not appear to work with addons

### ISSUE THREAD

**Issue by runspired** [simonihmig/ember-cli-bundle-analyzer#25]
Was hoping to use this to inspect the size of modules in the dummy app built for an addon, but it does not appear to work for such.

**Comment by simonihmig** [comment]
@runspired thanks for reporting! Do you see the loading page on `/_analyze`? If so, does it never stop loading, or what exactly happens?

Fwiw, the tests in this addon work with the addon's own dummy app, but maybe the case is different when used as a dependency in a different addon!?

**Comment by runspired** [comment]
I get an unrecognized url error so it seems it’s not getting registered. Digging through the code I don’t see an obvious reason for why that would be the case. It was in devDeoendencies, maybe I needed it in dependencies: will check.

**Comment by simonihmig** [comment]
Is it open-source? I can take a look if it is...

**Comment by runspired** [comment]
@simonihmig it is but I've pivoted away from it being an ember addon, and am only marginally continuing to use ember-cli as a harness (I'm building a performance reproduction app for a specific set of scenarios for the chrome team and all the extra framework stuff was getting in the way in the profiler of showing what I was trying to show)
