### ISSUE TITLE
Ember Engines support?

### ISSUE THREAD

**Issue by jfrux** [simonihmig/ember-cli-bundle-analyzer#36]
Wasn't sure if it was officially supported or not.

**Comment by simonihmig** [comment]
Tbh, I don't know, as I am not an engines user and not sure what it takes to support it. I think it all depends on `broccoli-concat` to emit the stats output for the engine's bundles, and it could very well already do that, but I am not sure.

**Comment by simonihmig** [comment]
If there was an issue here, then it will very likely been fixed by #26
