### ISSUE TITLE
Error: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by jeanduplessis** [simonihmig/ember-cli-bundle-analyzer#7]
Tried running the analyzer on our Ember app and getting the above error.

Env:
- macOS 10.14
- ember/ember-cli 3.4.1
- watchman 4.9.0 (throws similar error without watchman as well)

Console output:
<img width="1222" alt="screenshot 2018-10-21 at 07 55 35" src="https://user-images.githubusercontent.com/492942/47263695-0b8bd180-d507-11e8-9fbe-1300ca431df0.png">

**Comment by simonihmig** [comment]
#26 has been almost a rewrite of this adddon, which likely does not suffer from this. Closing therefore.
